//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netframwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class pks_cohoivieclam
    {
        public System.Guid soid { get; set; }
        public string ma_chinhanh { get; set; }
        public Nullable<System.DateTime> ngay_khaosat { get; set; }
        public string kh_hoten { get; set; }
        public string kh_diachi { get; set; }
        public string kh_dienthoai { get; set; }
        public string kh_diadiem_khaosat { get; set; }
        public string kh_congviec { get; set; }
        public string kh_sogio_lamviec { get; set; }
        public string kh_congviec_hailong { get; set; }
        public string kh_thunhap_chiphihangngay { get; set; }
        public string kh_thunhap_chiphihangngay_tietkiem { get; set; }
        public string kh_thunhap_chiphihangngay_dulich_khac { get; set; }
        public string kh_thunhap_cao { get; set; }
        public string kh_thunhap_cao_lamthem { get; set; }
        public string kh_thunhap_cao_dautukinhdoanh { get; set; }
        public string kh_thunhap_cao_thangtien { get; set; }
        public string kh_thunhap_cao_khac { get; set; }
        public string kh_congviec_chon_thoigianlinhhoat { get; set; }
        public string kh_congviec_chon_theokhanang { get; set; }
        public string kh_congviec_chon_theokhanangthangtien { get; set; }
        public string kh_congviec_chon_theocohoihochoi_dulich { get; set; }
        public string kh_congviec_chon_theokhac { get; set; }
        public string kh_dongytimhieu { get; set; }
        public string kh_thoigian_thamgia { get; set; }
        public string ma_nv_phutrach { get; set; }
        public string ctv_ten { get; set; }
        public string ctv_dienthoai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
