//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netframwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class pks_duhoc_capquyenuutien
    {
        public System.Guid soid { get; set; }
        public string ma_chinhanh { get; set; }
        public Nullable<System.DateTime> ngay_khaosat { get; set; }
        public string cha_hoten { get; set; }
        public string cha_nghenghiep { get; set; }
        public string me_hoten { get; set; }
        public string me_nghenghiep { get; set; }
        public string diachi_nha { get; set; }
        public string dienthoai { get; set; }
        public string diachi { get; set; }
        public string tc_01_kehoach { get; set; }
        public string tc_02_khokhan { get; set; }
        public string tc_03_lolang { get; set; }
        public string tc_04_dinhuongduhoc { get; set; }
        public string tc_05_cungthamdu { get; set; }
        public string ma_nv_phutrach { get; set; }
        public string ten_ctv { get; set; }
        public Nullable<int> thoigian_thamdu { get; set; }
        public string kehoach_nghihuu { get; set; }
        public Nullable<System.DateTime> ngay_thamdu { get; set; }
        public string so_dienthoai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
