//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netframwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class pks_nhucaukhachhang
    {
        public System.Guid soid { get; set; }
        public string ma_chinhanh { get; set; }
        public Nullable<System.DateTime> ngay_khaosat { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string dienthoai { get; set; }
        public string diachi_nharieng { get; set; }
        public string noilamviec { get; set; }
        public string nghenghiep { get; set; }
        public string tinhtranghonnhan { get; set; }
        public string ma_nv_phutrach { get; set; }
        public string ten_ctv { get; set; }
        public Nullable<int> thoigian_thamdu { get; set; }
        public string kehoach_nghihuu { get; set; }
        public Nullable<System.DateTime> ngay_thamdu { get; set; }
        public string so_dienthoai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
