//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bc_thunhap_nhanvien_chitiet
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> soid { get; set; }
        public string ma_hopdongbaohiem_loai { get; set; }
        public string loaidong_tinhluong { get; set; }
        public string loaidong_nam { get; set; }
        public string loai_phinhantho { get; set; }
        public string ma_nv { get; set; }
        public string ma_chucvu { get; set; }
        public string sotk_nganhang { get; set; }
        public string ma_nganhang { get; set; }
        public string ma_chinhanh { get; set; }
        public string ten_chinhanh { get; set; }
        public string ma_nhanh_gad { get; set; }
        public string is_gad { get; set; }
        public string ma_tinhthanhpho { get; set; }
        public string ma_doituong_mua { get; set; }
        public string ma_nv_phutrach { get; set; }
        public string ma_chucvu_phutrach { get; set; }
        public string ma_nv_hoahong { get; set; }
        public string ma_chucvu_hoahong { get; set; }
        public string ma_doituong_doitac { get; set; }
        public Nullable<System.Guid> hopdong_baohiem_soid { get; set; }
        public string hopdong_baohiem_so { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_nop { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_phathanh { get; set; }
        public string is_kichhoat21ngay { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_ack { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_pass_ack { get; set; }
        public Nullable<System.DateTime> ngayky_tinhphi_tieptheo { get; set; }
        public Nullable<System.DateTime> tungay_dot_thanhtoan { get; set; }
        public Nullable<System.DateTime> denngay_dot_thanhtoan { get; set; }
        public string ma_hh { get; set; }
        public string ten_hh { get; set; }
        public string is_sanpham_chinh { get; set; }
        public Nullable<decimal> tyle_hoahong_sp { get; set; }
        public Nullable<decimal> thoigian_baove { get; set; }
        public string ma_doituong_baohiem { get; set; }
        public Nullable<decimal> sotien_baohiem { get; set; }
        public Nullable<decimal> sotien_phi_fyp { get; set; }
        public Nullable<decimal> sotien_thunhap_tamtinh { get; set; }
        public Nullable<decimal> tyle_hoahong { get; set; }
        public Nullable<decimal> tyle_hoahong_hoahong { get; set; }
        public Nullable<decimal> doanhso_fyp { get; set; }
        public Nullable<decimal> doanhso_pfyp { get; set; }
        public Nullable<decimal> lechbac { get; set; }
        public Nullable<decimal> hoahong { get; set; }
        public Nullable<decimal> thunhap_lechbac { get; set; }
        public Nullable<decimal> thunhap { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
