//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bc_thunhap_nhanvien
    {
        public System.Guid soid { get; set; }
        public Nullable<System.DateTime> tungay_dot_thanhtoan { get; set; }
        public Nullable<System.DateTime> denngay_dot_thanhtoan { get; set; }
        public string ma_nv { get; set; }
        public string namthang { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public string ma_nganhang { get; set; }
        public string sotk_nganhang { get; set; }
        public string ma_chucvu { get; set; }
        public string ma_chinhanh { get; set; }
        public Nullable<decimal> tong_fyp { get; set; }
        public Nullable<decimal> tong_pfyp { get; set; }
        public Nullable<decimal> thunhap_canhan { get; set; }
        public Nullable<decimal> thunhap_hethong { get; set; }
        public Nullable<decimal> thunhap_tong { get; set; }
        public Nullable<decimal> thunhap_donghuong { get; set; }
        public Nullable<decimal> thunhap_khac { get; set; }
        public Nullable<decimal> thunhap_truocthue { get; set; }
        public Nullable<decimal> sotien_thue { get; set; }
        public Nullable<decimal> thunhap_tamgiu { get; set; }
        public Nullable<decimal> sotien_khautru { get; set; }
        public Nullable<decimal> thunhap_thuan_trongky { get; set; }
        public Nullable<decimal> thunhap_chiuthue_tichluy { get; set; }
        public Nullable<decimal> sotien_thue_khautru { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
