//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bc_tonghop_hopdongbaohiem_phinhantho
    {
        public System.Guid soid { get; set; }
        public Nullable<int> stt { get; set; }
        public string hopdong_doitac_quanly { get; set; }
        public string hopdong_tensanpham { get; set; }
        public string hopdong_so { get; set; }
        public string hopdong_ngayphatsinh_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngayphatsinh { get; set; }
        public string hopdong_ngayhieuluc_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngayhieuluc { get; set; }
        public string hopdong_ngayketthuc_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngayketthuc { get; set; }
        public string hopdong_cmnd_kh { get; set; }
        public string hopdong_ma_kh { get; set; }
        public string hopdong_ten_kh { get; set; }
        public Nullable<decimal> hopdong_sotien_phibaoiem { get; set; }
        public string hopdong_ma_doitac { get; set; }
        public string hopdong_ma_chinhanh { get; set; }
        public string hopdong_ma_nhanh_gad { get; set; }
        public string hopdong_is_gad { get; set; }
        public string hopdong_ma_nv_phutrach { get; set; }
        public string hopdong_ma_hh { get; set; }
        public string hopdong_ma_tinhthanhpho { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
