//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bc_tonghop_hopdongbaohiem_hwl
    {
        public System.Guid soid { get; set; }
        public Nullable<int> stt { get; set; }
        public string hopdong_so { get; set; }
        public string hopdong_ngay_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngay { get; set; }
        public string doituong_mua_cmd { get; set; }
        public string doituong_mua_ten { get; set; }
        public string hopdong_ngaynop_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngaynop { get; set; }
        public string hopdong_ngayphathanh_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngayphathanh { get; set; }
        public string hopdong_tinhtrang { get; set; }
        public string hopdong_ma_tinhtrang { get; set; }
        public Nullable<decimal> hopdong_phibaohiem { get; set; }
        public Nullable<decimal> hopdong_phidongthem { get; set; }
        public Nullable<decimal> hopdong_tongphibaohiem { get; set; }
        public string hopdong_ngay_thuphi_hientai_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngay_thuphi_hientai { get; set; }
        public string hopdong_ngay_kyphi_tieptheo_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngay_kyphi_tieptheo { get; set; }
        public string hopdong_ngayky_ack_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngayky_ack { get; set; }
        public string hopdong_dinhkydongphi { get; set; }
        public string hopdong_ma_dinhkydong_phi { get; set; }
        public string hopdong_ma_hh { get; set; }
        public string hopdong_tensanpham { get; set; }
        public string hopdong_tinhtrang2 { get; set; }
        public string hopdong_tintrang_sp { get; set; }
        public Nullable<decimal> hopdong_phisanpham { get; set; }
        public string hopdong_manguoi_duocbaohiem { get; set; }
        public string hopdong_tennguoi_duocbaohiem { get; set; }
        public string hopdong_ngaynop_phisanpham_text { get; set; }
        public Nullable<System.DateTime> hopdong_ngaynop_phisanpham { get; set; }
        public Nullable<int> hopdong_thoihan { get; set; }
        public Nullable<int> hopdong_thoihan_sp { get; set; }
        public Nullable<decimal> hopdong_phi_sanpham_chinh_phu { get; set; }
        public Nullable<decimal> hopdong_phi_sanpham_them { get; set; }
        public string hopdong_maso_phucvu { get; set; }
        public string hopdong_tenso_phucvu { get; set; }
        public string hopdong_maso_tvbh_gioithieu { get; set; }
        public string hopdong_ten_tvbh_gioithieu { get; set; }
        public string hopdong_maso_bangminhhoa { get; set; }
        public string hopdong_sdt_chu { get; set; }
        public string hopdong_email_chu { get; set; }
        public Nullable<decimal> hopdong_sotien_baohiem { get; set; }
        public string hopdong_diachi_khachang { get; set; }
        public Nullable<System.DateTime> hopdong_ngaysinh_khachhang { get; set; }
        public string hopdong_ma_chinhanh { get; set; }
        public string hopdong_ma_nv_phutrach { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
        public string ma_tinhthanhpho { get; set; }
    }
}
