//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_hopdongbaohiem_kythuphi
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> soid { get; set; }
        public Nullable<System.DateTime> ngayct_ct { get; set; }
        public Nullable<int> stt { get; set; }
        public string ma_hopdongbaohiem_loai { get; set; }
        public string ma_doituong_baohiem { get; set; }
        public string hopdongbaohiem_so { get; set; }
        public string ma_nv_tuvan { get; set; }
        public string ma_nv_phutrach { get; set; }
        public string ma_nv_quanly { get; set; }
        public string ma_vanphong { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_nop { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_phathanh { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_ack { get; set; }
        public Nullable<System.DateTime> hopdong_baohiem_ngay_pass_ack { get; set; }
        public Nullable<System.DateTime> ngayky_tinhphi_tieptheo { get; set; }
        public string ma_dinhky_dongphi { get; set; }
        public Nullable<int> loai_kydongphi { get; set; }
        public Nullable<decimal> sotien_phi_fyp { get; set; }
        public Nullable<decimal> sotien_phi_fyp_dathu { get; set; }
        public Nullable<System.DateTime> tungay_dot_thanhtoan { get; set; }
        public Nullable<System.DateTime> denngay_dot_thanhtoan { get; set; }
        public string ma_hopdongbaohiem_tinhtrang { get; set; }
        public Nullable<int> xacnhan_nv_thuphi { get; set; }
        public Nullable<System.DateTime> ngayxacnhan_nv_thuphi { get; set; }
        public string nguoixacnhan_nv_thuphi { get; set; }
        public Nullable<int> xacnhan_cty_thuphi { get; set; }
        public Nullable<System.DateTime> ngayxacnhan_cty_thuphi { get; set; }
        public string nguoixacnhan_cty_thuphi { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
