//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_hopdongbaohiem_tailieu
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> soid { get; set; }
        public string id_kythuphi { get; set; }
        public string hopdong_baohiem_so { get; set; }
        public Nullable<System.DateTime> ngayct_ct { get; set; }
        public Nullable<int> stt { get; set; }
        public string tailieu_loai { get; set; }
        public string tailieu_extension { get; set; }
        public string tailieu_name { get; set; }
        public string tailieu_url { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
