//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_hopdongbaohiem_ct
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> soid { get; set; }
        public Nullable<System.Guid> soid_hopdongbaohiem_phinhantho { get; set; }
        public Nullable<System.DateTime> ngayct_ct { get; set; }
        public Nullable<int> stt { get; set; }
        public string ma_hh { get; set; }
        public string ma_doituong_baohiem { get; set; }
        public Nullable<decimal> thoigian_baove { get; set; }
        public Nullable<decimal> sotien_baohiem { get; set; }
        public Nullable<decimal> sotien_phi_fyp { get; set; }
        public Nullable<decimal> tyle_hoahong { get; set; }
        public Nullable<decimal> sotien_thunhap_tamtinh { get; set; }
        public Nullable<decimal> heso_fyp { get; set; }
        public Nullable<decimal> sotien_phi_pfyp { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
