//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_tyle_hoahong_sanpham_phu_ct
    {
        public System.Guid id { get; set; }
        public System.Guid soid { get; set; }
        public string ma_bang { get; set; }
        public string ma_hh { get; set; }
        public string is_tinh_thoigian_baove { get; set; }
        public Nullable<int> tu_nam { get; set; }
        public Nullable<int> den_nam { get; set; }
        public Nullable<decimal> hoahong { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
