//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ChuDe
    {
        public string id { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string ghichu { get; set; }
    }
}
