//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DoiTac_NhaCungCap_SanPham
    {
        public System.Guid id { get; set; }
        public string ma_doitac_nhacungcap { get; set; }
        public string ma_hh_nhacungcap { get; set; }
        public string ma_hh { get; set; }
        public string ten_hh { get; set; }
        public string ten_thuongmai { get; set; }
        public string ten_loai_hh { get; set; }
        public string quycach { get; set; }
        public string ten_dvt { get; set; }
        public string mota_hh { get; set; }
        public Nullable<System.DateTime> ngayapdung { get; set; }
        public Nullable<decimal> dongia_goc { get; set; }
        public Nullable<decimal> dongia_ban { get; set; }
        public Nullable<decimal> tyle_ck_nhanvien { get; set; }
        public Nullable<decimal> tyle_ck_khachhang { get; set; }
        public Nullable<decimal> tyle_ck { get; set; }
        public string ma_hh_nhom { get; set; }
        public string ghichu { get; set; }
        public string is_hot { get; set; }
        public string is_giamgia { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
