//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DoiTuong_LienHe
    {
        public System.Guid id { get; set; }
        public string ma_doituong { get; set; }
        public Nullable<int> stt { get; set; }
        public string nguoilienhe { get; set; }
        public string chucdanh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string dienthoai { get; set; }
        public string line_noibo { get; set; }
        public string didong { get; set; }
        public string email_cty { get; set; }
        public string email_canhan { get; set; }
        public string zalo { get; set; }
        public string viber { get; set; }
        public string facebook { get; set; }
        public string ghichu { get; set; }
        public string macdinh { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
