//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DoiTac
    {
        public System.Guid id { get; set; }
        public string ma_doitac { get; set; }
        public string ten_doitac { get; set; }
        public string is_thunhap_tamtinh { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public string thongtin_lienhe { get; set; }
        public string hinhanh_gioithieu { get; set; }
        public string ghichu_gioithieu { get; set; }
        public string noidung_gioithieu { get; set; }
        public string gioithieu_gioithieu { get; set; }
        public Nullable<bool> is_hot { get; set; }
        public Nullable<bool> is_top { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
        public string ma_doitac_old { get; set; }
    }
}
