//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DoiTac_SanPham
    {
        public System.Guid id { get; set; }
        public string ma_doitac { get; set; }
        public string ten_doitac { get; set; }
        public string ma_hh { get; set; }
        public string ten_hh { get; set; }
        public string ma_sanpham_loai { get; set; }
        public string ten_sanpham_loai { get; set; }
        public string ma_hh_cha { get; set; }
        public string is_sanpham_chinh { get; set; }
        public Nullable<decimal> heso_pfyp_canhan { get; set; }
        public Nullable<decimal> heso_quanly1 { get; set; }
        public Nullable<decimal> heso_quanly2 { get; set; }
        public Nullable<decimal> heso_vanphong { get; set; }
        public Nullable<decimal> tyle_hoahong_nam2 { get; set; }
        public Nullable<decimal> heso_fyp_phi_nhantho { get; set; }
        public Nullable<decimal> thoihan_baove { get; set; }
        public Nullable<decimal> sotien_baohiem { get; set; }
        public Nullable<decimal> phi_baohiem { get; set; }
        public Nullable<decimal> tyle_hoahong { get; set; }
        public Nullable<decimal> heso_hoahong { get; set; }
        public Nullable<int> stt { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public string hinhanh_gioithieu { get; set; }
        public string tieude_gioithieu { get; set; }
        public string noidung_gioithieu { get; set; }
        public Nullable<bool> is_new_gioithieu { get; set; }
        public Nullable<bool> is_hot_gioithieu { get; set; }
        public Nullable<int> stt_gioithieu { get; set; }
        public Nullable<bool> anhien_gioithieu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
