//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DoiTuong
    {
        public System.Guid id { get; set; }
        public string ma_doituong_loai { get; set; }
        public string ma_doituong { get; set; }
        public string ten_doituong { get; set; }
        public string ten_viettat { get; set; }
        public string is_doitac { get; set; }
        public string is_khachhang { get; set; }
        public string is_nhacungcap { get; set; }
        public string is_nhanvien { get; set; }
        public string is_congtacvien { get; set; }
        public string is_vay { get; set; }
        public string is_thue { get; set; }
        public string is_khac { get; set; }
        public string ma_taikhoan_chiphi { get; set; }
        public string ma_doituong_nhom { get; set; }
        public string ma_tinhthanhpho { get; set; }
        public string ma_quanhuyen { get; set; }
        public string ma_phuongxa { get; set; }
        public string diachi { get; set; }
        public string diachi_full { get; set; }
        public string masothue { get; set; }
        public string hoadon_mauso { get; set; }
        public string hoadon_kyhieu { get; set; }
        public string dienthoai { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public string website { get; set; }
        public string cmnd_maso { get; set; }
        public Nullable<System.DateTime> cmnd_ngaycap { get; set; }
        public string cmnd_noicap { get; set; }
        public string ma_gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string ghichu { get; set; }
        public string ma_nv_phutrach { get; set; }
        public string ma_doituong_old { get; set; }
        public string is_tudong { get; set; }
        public string is_nhantho { get; set; }
        public string is_phi_nhantho { get; set; }
        public string is_ketnoigiaothuong { get; set; }
        public string loai_phinhantho { get; set; }
        public string is_gad { get; set; }
        public string ma_nhanh_gad { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
        public Nullable<bool> is_bandieuhanh { get; set; }
        public string ma_chucvu { get; set; }
        public string hinhanh { get; set; }
        public string chucvu_mota { get; set; }
        public string mota_hocvan { get; set; }
    }
}
