//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DangKyTuVan
    {
        public int ma { get; set; }
        public string ten { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string mail { get; set; }
        public string ma_tinhthanhpho { get; set; }
        public string ma_quanhuyen { get; set; }
        public string ma_phuongxa { get; set; }
        public string noidung { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
    }
}
