//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HoatDong
    {
        public System.Guid id { get; set; }
        public string ma_hoatdong { get; set; }
        public string ten_hoatdong { get; set; }
        public string ma_nhanh_gad { get; set; }
        public string ma_chucvu_gad { get; set; }
        public string ma_hoadong_nhom { get; set; }
        public string is_chung { get; set; }
        public string is_gad { get; set; }
        public Nullable<int> mausac { get; set; }
        public Nullable<int> stt { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public string database_name { get; set; }
        public string phienban { get; set; }
    }
}
