//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HangTonKho
    {
        public System.Guid id { get; set; }
        public string ma_hh { get; set; }
        public string ten_hh { get; set; }
        public string ten_viettat { get; set; }
        public string ten_thuongmai { get; set; }
        public string ten_tienganh { get; set; }
        public string dv_tinh { get; set; }
        public string ma_taikhoan { get; set; }
        public string loaihangtonkho { get; set; }
        public Nullable<decimal> soluong_antoan { get; set; }
        public Nullable<decimal> soluong_toithieu { get; set; }
        public Nullable<decimal> songay_denghi { get; set; }
        public Nullable<decimal> songay_mua { get; set; }
        public string cachmuahang { get; set; }
        public string is_denghimua { get; set; }
        public string is_denghichuyenkho { get; set; }
        public Nullable<int> tuoitho { get; set; }
        public string ma_loaithue { get; set; }
        public Nullable<decimal> tyle_vat { get; set; }
        public string quycach { get; set; }
        public string tinhchat { get; set; }
        public byte[] hinhanh { get; set; }
        public string hinhanh_url { get; set; }
        public string is_tudong { get; set; }
        public string is_sohuu_doitac { get; set; }
        public string is_sohuu_congty { get; set; }
        public string ghichu { get; set; }
        public string ma_hh_old { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
