//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoaiChungTu
    {
        public System.Guid id { get; set; }
        public string ma_loaichungtu { get; set; }
        public string ten_loaichungtu { get; set; }
        public string ma_loaichungtu_nhom { get; set; }
        public string ma_loaichungtu_nsd { get; set; }
        public Nullable<int> stt_count { get; set; }
        public string table_name { get; set; }
        public string linkweb { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
