//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NghiepVu
    {
        public System.Guid id { get; set; }
        public string ma_nghiepvu { get; set; }
        public string ten_nghiepvu { get; set; }
        public string tk_no_tonghop { get; set; }
        public string tk_co_tonghop { get; set; }
        public string tk_no { get; set; }
        public string tk_co { get; set; }
        public Nullable<int> loainv { get; set; }
        public string ma_loaict { get; set; }
        public string is_macdinh { get; set; }
        public Nullable<int> stt { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
