//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_nhanvien_phinhantho
    {
        public System.Guid id { get; set; }
        public string ma_nv { get; set; }
        public string ten_nv { get; set; }
        public string ma_nv_tuyendung { get; set; }
        public string ma_nv_old { get; set; }
        public string is_truongnhanh { get; set; }
        public string is_quanly_capcao { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public string ma_chucvu_phinhantho { get; set; }
        public string ma_nhanh_phinhantho { get; set; }
        public string ma_chucvu_gad { get; set; }
        public string is_ngunghoatdong { get; set; }
        public string ma_bac_doanhnhan { get; set; }
        public string ma_bac_doanhnhan_old { get; set; }
        public string maso_quetthe { get; set; }
        public Nullable<System.DateTime> ngayvaolam { get; set; }
        public Nullable<System.DateTime> ngayvaocongdoan { get; set; }
        public Nullable<System.DateTime> ngaynghiviec { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string ma_gioitinh { get; set; }
        public string dienthoai { get; set; }
        public string email { get; set; }
        public string cmnd { get; set; }
        public Nullable<System.DateTime> cmnd_ngaycap { get; set; }
        public string cmnd_noicap { get; set; }
        public string ma_quoctich { get; set; }
        public string ma_dantoc { get; set; }
        public string ma_tongiao { get; set; }
        public string diachi_noisinh { get; set; }
        public string ma_tinhthanhpho_noisinh { get; set; }
        public string ma_quanhuyen_noisinh { get; set; }
        public string ma_phuongxa_noisinh { get; set; }
        public string diachi_thuongtru { get; set; }
        public string ma_tinhthanhpho_thuongtru { get; set; }
        public string ma_tinhthanhpho_thuongtru_old { get; set; }
        public string ma_quanhuyen_thuongtru { get; set; }
        public string ma_phuongxa_thuongtru { get; set; }
        public string diachi_tamtru { get; set; }
        public string ma_tinhthanhpho_tamtru { get; set; }
        public string ma_quanhuyen_tamtru { get; set; }
        public string ma_phuongxa_tamtru { get; set; }
        public string nguoilienhe { get; set; }
        public string dienthoai_lienhe { get; set; }
        public string diachi_lienhe { get; set; }
        public string ma_tinhthanhpho_lienhe { get; set; }
        public string ma_quanhuyen_lienhe { get; set; }
        public string ma_phuongxa_lienhe { get; set; }
        public string maso_sohokhau { get; set; }
        public string tenchu_sohokhau { get; set; }
        public string ngaysinh_chuhokhau { get; set; }
        public string quanhe_chuhokhau { get; set; }
        public string gioitinh_chuhokhau { get; set; }
        public string dantoc_chuhokhau { get; set; }
        public string sotk_nganhang { get; set; }
        public string ma_nganhang { get; set; }
        public string ma_nganhang_old { get; set; }
        public string chutaikhoan { get; set; }
        public string ma_tinhthanhpho_chinhanh_nganhang { get; set; }
        public string ma_quanhuyen_chinhanh_nganhang { get; set; }
        public string chinhanh_nganhang { get; set; }
        public string maso_thue { get; set; }
        public string maso_solaodong { get; set; }
        public string maso_sobaohiemxahoi { get; set; }
        public string maso_sobaohiemyte { get; set; }
        public string ma_tinhtranghonnhan { get; set; }
        public string ma_trinhdochuyenmon { get; set; }
        public string ma_hinhthuctinhluong { get; set; }
        public string ma_hinhthuctraluong { get; set; }
        public string ma_taikhoan_chiphi { get; set; }
        public string xuatnhapcanh { get; set; }
        public string passport { get; set; }
        public string giaypheplaodong { get; set; }
        public string diachi_nuocngoai { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
