//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NganHang_PhongGiaoDich
    {
        public System.Guid id { get; set; }
        public string ma_phonggiaodich { get; set; }
        public string ten_phonggiaodich { get; set; }
        public string ma_nganhang { get; set; }
        public string ma_tinhthanhpho { get; set; }
        public string ma_quanhuyen { get; set; }
        public string ma_phuongxa { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
