//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TaiSan
    {
        public System.Guid id { get; set; }
        public Nullable<int> stt { get; set; }
        public string ma_taisan { get; set; }
        public string ten_taisan { get; set; }
        public string ten_viettat { get; set; }
        public string dv_tinh { get; set; }
        public string ma_taisan_loai { get; set; }
        public string ma_taisan_loaihinh { get; set; }
        public string ma_taisan_nhom { get; set; }
        public Nullable<System.DateTime> ngaymua { get; set; }
        public string model { get; set; }
        public string congnghe_sx { get; set; }
        public string nuoc_sx { get; set; }
        public string nam_sx { get; set; }
        public string quycach { get; set; }
        public string tinhnang { get; set; }
        public Nullable<decimal> trongluong { get; set; }
        public Nullable<decimal> chieudai { get; set; }
        public Nullable<decimal> chieurong { get; set; }
        public Nullable<decimal> chieucao { get; set; }
        public string congsuat { get; set; }
        public string congnghe_nuoc { get; set; }
        public string ghichu { get; set; }
        public int khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
