//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TaiLieu_Nhom
    {
        public System.Guid id { get; set; }
        public string ma_nhom_tailieu { get; set; }
        public string ten_nhom_tailieu { get; set; }
        public string loai_nhom_tailieu { get; set; }
        public Nullable<int> cap_nhom { get; set; }
        public string IconImg { get; set; }
        public string url { get; set; }
        public string phanquyen_nsd { get; set; }
        public string ma_nhom_tailieu_cha { get; set; }
        public Nullable<bool> khong_hienthi { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
