//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TaiKhoan
    {
        public System.Guid id { get; set; }
        public string ma_taikhoan { get; set; }
        public string ten_taikhoan { get; set; }
        public string ma_taikhoan_nhom { get; set; }
        public Nullable<int> loai_taikhoan { get; set; }
        public Nullable<int> cap_taikhoan { get; set; }
        public string ghichu { get; set; }
        public string loaitk_ma_chungkhoan { get; set; }
        public string loaitk_ma_codong { get; set; }
        public string loaitk_ma_congcu { get; set; }
        public string loaitk_ma_ctv { get; set; }
        public string loaitk_ma_congtrinh { get; set; }
        public string loaitk_ma_doituong { get; set; }
        public string loaitk_ma_doituong_gui { get; set; }
        public string loaitk_ma_hh { get; set; }
        public string loaitk_ma_hdkd { get; set; }
        public string loaitk_ma_kmp { get; set; }
        public string loaitk_ma_lctt { get; set; }
        public string loaitk_sotk_nganhang { get; set; }
        public string loaitk_ma_phongban { get; set; }
        public string loaitk_ma_quytienmat { get; set; }
        public string loaitk_ma_taisan { get; set; }
        public string loaitk_ma_ttcp { get; set; }
        public string loaitk_ma_xdcb { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
