//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_UngVien
    {
        public System.Guid id { get; set; }
        public string ma_uv { get; set; }
        public string ten_uv { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string so_cmnd { get; set; }
        public Nullable<System.DateTime> ngaycap_cmnd { get; set; }
        public string noicap_cmnd { get; set; }
        public string diachi_thuongtru { get; set; }
        public string noiohientai { get; set; }
        public string so_dienthoai { get; set; }
        public string email { get; set; }
        public string ma_sothue { get; set; }
        public string so_taikhoan_nganhang { get; set; }
        public string ten_nganhang { get; set; }
        public string chinhanh_nganhang { get; set; }
        public string trinhdo_hocvan { get; set; }
        public string trinhdo_hocvan_khac { get; set; }
        public string tinhtrang_honnhan { get; set; }
        public string tinhtrang_honnhan_socon { get; set; }
        public string nguoigioithieu_ten { get; set; }
        public string nguoigioithieu_chucvu { get; set; }
        public string nguoigioithieu_dienthoai { get; set; }
        public string hinhanh_canhan { get; set; }
        public string vitri_ungtuyen { get; set; }
        public string nganhnghe_lamviec { get; set; }
        public Nullable<System.DateTime> ngay_dangky { get; set; }
        public string ma_nv_tuyendung { get; set; }
        public Nullable<int> duyet_dondangky { get; set; }
        public string ma_chinhanh_duyet { get; set; }
        public string ma_nv_tuyendung_duyet { get; set; }
        public string nguoiduyet { get; set; }
        public Nullable<System.DateTime> ngayduyet { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
        public Nullable<bool> is_nopphieuphongvan { get; set; }
        public Nullable<System.DateTime> ngay_nopphieuphongvan { get; set; }
        public Nullable<System.DateTime> ngay_henphongvan { get; set; }
        public string diadiem_henphongvan { get; set; }
        public Nullable<int> duyet_henphongvan { get; set; }
        public string phongvan_mucthuphidenghi { get; set; }
        public Nullable<System.DateTime> phongvan_ngaynhanviec { get; set; }
        public string phongvan_danhgiachung { get; set; }
        public Nullable<decimal> phongvan_thunhap_denghi { get; set; }
        public string phongvan_nguoiphongvan { get; set; }
        public Nullable<int> phongvan_lanphongvan { get; set; }
        public Nullable<int> is_phongvan_ketqua { get; set; }
        public Nullable<System.DateTime> ngay_phongvan { get; set; }
        public Nullable<bool> is_nopphieuphongvan_daky { get; set; }
        public Nullable<System.DateTime> ngay_nopphieuphongvan_daky { get; set; }
        public string hinhanh_cmnd_mattruoc { get; set; }
        public string hinhanh_cmnd_matsau { get; set; }
        public Nullable<bool> is_kichhoat { get; set; }
        public Nullable<System.DateTime> ngay_kichhoat { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public Nullable<bool> is_phongvan_online { get; set; }
        public string link_phongvan_online { get; set; }
        public string is_offline { get; set; }
        public string is_thamgia_hoithao { get; set; }
        public string is_banhang { get; set; }
    }
}
