//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_UngVien_ThongTinGiaDinh
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> id_uv { get; set; }
        public string hoten { get; set; }
        public string quoctich { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string moiquanhe { get; set; }
        public string nghenghiep { get; set; }
        public string coquan { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<int> daxoa { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
        public string ghichu { get; set; }
    }
}
