//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu_DM_TinTuc
    {
        public string ma { get; set; }
        public string loaitin { get; set; }
        public string ten { get; set; }
        public string tieude { get; set; }
        public string noidung { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string ghichu { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> istrangchu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<bool> ishot { get; set; }
        public Nullable<bool> isnew { get; set; }
        public string quocgia { get; set; }
    }
}
