//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu_DuHoc_DangKy
    {
        public string ma { get; set; }
        public string ten { get; set; }
        public string ten_phuhuynh { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string mail { get; set; }
        public string ma_tinhthanhpho { get; set; }
        public string ma_quanhuyen { get; set; }
        public string ma_phuongxa { get; set; }
        public string noidung { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string passport_hinhanh { get; set; }
        public string giaykhaisinh_hinhanh { get; set; }
        public string bangdiem_tiengviet_hinhanh { get; set; }
        public string bangdiem_tienganh_hinhanh { get; set; }
        public string cmdd_phuhuynh_hinhanh { get; set; }
        public string hinhanh_khac { get; set; }
        public string ma_chude { get; set; }
    }
}
