//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu_DuHocQuocTe_PhieuDangKyThongTin
    {
        public string id { get; set; }
        public Nullable<System.DateTime> ngay_dangki { get; set; }
        public string diadiem { get; set; }
        public string nguoidaidien { get; set; }
        public string chame_hoten { get; set; }
        public Nullable<System.DateTime> chame_ngaysinh { get; set; }
        public string chame_nghenghiep { get; set; }
        public string chame_diachi_lienlac { get; set; }
        public string chame_dienthoai_NR { get; set; }
        public string chame_dienthoai_coquan { get; set; }
        public string chame_dienthoai_didong { get; set; }
        public string phuhuyen_camnghi { get; set; }
        public string phuhuyen_vande { get; set; }
        public string phuhuyen_lolang { get; set; }
        public string phuhuyen_xetchon { get; set; }
        public string hocsinh_hoten { get; set; }
        public string hocsinh_xeploai { get; set; }
        public Nullable<System.DateTime> hocsinh_ngaysinh { get; set; }
        public string hocsinh_gioitinh { get; set; }
        public string hocsinh_hoten_01 { get; set; }
        public string hocsinh_xeploai_01 { get; set; }
        public Nullable<System.DateTime> hocsinh_ngaysinh_01 { get; set; }
        public string hocsinh_gioitinh_01 { get; set; }
        public Nullable<System.DateTime> thoigianlienhe { get; set; }
        public string phuhuynh_kyten { get; set; }
        public string gioithieu_hoten { get; set; }
        public string gioithieu_diachi { get; set; }
        public string gioithieu_dienthoai { get; set; }
        public string gioithieu_moiquanhe { get; set; }
        public string gioithieu_hoten_01 { get; set; }
        public string gioithieu_diachi_01 { get; set; }
        public string gioithieu_dienthoai_01 { get; set; }
        public string gioithieu_moiquanhe_01 { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> daxoa { get; set; }
    }
}
