//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu_DM_DuHoc_TruongHoc
    {
        public string ma { get; set; }
        public string ten { get; set; }
        public string hinhanh { get; set; }
        public string gioithieu { get; set; }
        public string noidung { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public Nullable<bool> is_top { get; set; }
        public Nullable<bool> is_hot { get; set; }
    }
}
