//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_chungtuduyet_thongtinduyet
    {
        public System.Guid id { get; set; }
        public string ma_loaict { get; set; }
        public Nullable<int> capduyet { get; set; }
        public Nullable<System.Guid> soid { get; set; }
        public Nullable<System.DateTime> ngayct { get; set; }
        public string soct { get; set; }
        public Nullable<System.Guid> id_ct { get; set; }
        public Nullable<int> duyetchungtu { get; set; }
        public Nullable<System.DateTime> ngayduyet { get; set; }
        public string nguoiduyet { get; set; }
        public Nullable<decimal> sotien_giaodich_duyet { get; set; }
        public Nullable<decimal> sotien_duyet { get; set; }
        public Nullable<decimal> soluong_giaodich_duyet { get; set; }
        public Nullable<decimal> soluong_duyet { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
