//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_dm_table
    {
        public string table_name { get; set; }
        public string table_caption { get; set; }
        public string table_parent { get; set; }
        public string khoadulieu { get; set; }
        public string ma_loaichungtu { get; set; }
        public string sql_select { get; set; }
        public string sql_insert { get; set; }
        public string sql_delete { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
