//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_dm_nsd
    {
        public System.Guid id { get; set; }
        public string ma_nsd { get; set; }
        public string ten_nsd { get; set; }
        public string matkhau { get; set; }
        public string ma_nsd_nhom { get; set; }
        public string is_nhomnsd { get; set; }
        public string ma_nv { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<int> stt { get; set; }
        public string is_tudong { get; set; }
        public Nullable<int> kichhoat_user { get; set; }
        public Nullable<System.DateTime> ngaykichhoat_user { get; set; }
        public string nguoikichoat_user { get; set; }
        public string ma_nsd_loai { get; set; }
        public string is_gad { get; set; }
        public string ma_nhanh_gad { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
