//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_phanquyen_email
    {
        public System.Guid id { get; set; }
        public string ma_loaict { get; set; }
        public string email_gui { get; set; }
        public string ten_hienthi { get; set; }
        public string matkhau { get; set; }
        public string mailserver { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> port { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string email_nhan { get; set; }
        public string email_cc { get; set; }
        public string email_bcc { get; set; }
        public string linkweb { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
