//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_rowlog
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> soid { get; set; }
        public string tablename { get; set; }
        public Nullable<System.DateTime> ngaytao_dulieu { get; set; }
        public string rowlog { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string database_name { get; set; }
    }
}
