//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_thongtindoanhnghiep
    {
        public System.Guid id { get; set; }
        public string ma_dv { get; set; }
        public string ten_dv { get; set; }
        public string ten_viettat { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string fax { get; set; }
        public string masothue { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string slogan { get; set; }
        public byte[] logo { get; set; }
        public string hinhanh_logo { get; set; }
        public Nullable<System.DateTime> ngaydautien { get; set; }
        public string hoadon_kyhieu { get; set; }
        public string hoadon_mauso { get; set; }
        public Nullable<int> hoadon_sokytu { get; set; }
        public string loaihoadon { get; set; }
        public string giamdoc { get; set; }
        public string ketoantruong { get; set; }
        public string thuquy { get; set; }
        public string thukho { get; set; }
        public string database_name { get; set; }
        public string ma_supper { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
    }
}
