//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kngt_dondathang_g
    {
        public System.Guid soid { get; set; }
        public string ma_chinhanh { get; set; }
        public string ma_kyketoan { get; set; }
        public string ma_loaict { get; set; }
        public Nullable<System.DateTime> ngayct { get; set; }
        public string soct { get; set; }
        public string ma_doitac_nhacungcap { get; set; }
        public string ten_doitac_nhacungcap { get; set; }
        public string thongtin_email_nhacungcap { get; set; }
        public Nullable<decimal> tyle_ck { get; set; }
        public string ma_doituong { get; set; }
        public string ten_doituong { get; set; }
        public string doituong_dienthoai_lienhe { get; set; }
        public string ma_tinhthanhpho { get; set; }
        public string ma_quanhuyen { get; set; }
        public string ma_phuongxa { get; set; }
        public string diachi_giaohang { get; set; }
        public Nullable<System.DateTime> ngayyeucaugiao { get; set; }
        public string ma_nv_phutrach { get; set; }
        public Nullable<decimal> sotien_phuphi { get; set; }
        public Nullable<decimal> sotien_thanhtoan { get; set; }
        public string ma_giaodich_nganhang { get; set; }
        public Nullable<System.DateTime> ngay_giaodich_nganhang { get; set; }
        public string sotk_nganhang_nhacungcap { get; set; }
        public string hinhanh_thanhtoan_nhacungcap { get; set; }
        public Nullable<decimal> sotien_thanhtoan_nhacungcap { get; set; }
        public Nullable<int> is_thanhtoan_nhacungcap { get; set; }
        public Nullable<int> is_xacnhan_nhacungcap { get; set; }
        public Nullable<System.DateTime> ngaygiaohang_nhacungcap { get; set; }
        public string ma_tinhthanhpho_nhacungcap { get; set; }
        public string diachi_giaohang_nhacungcap { get; set; }
        public Nullable<int> is_hoanthanh { get; set; }
        public Nullable<System.DateTime> ngayhoanthanh { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
