//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ns_nhanvien_quatrinhlamviec
    {
        public System.Guid id { get; set; }
        public string ma_nv { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public string mota { get; set; }
        public string ma_chinhanh { get; set; }
        public string ma_phongban { get; set; }
        public string ma_bophan { get; set; }
        public string ma_chucdanh { get; set; }
        public string ma_chucvu { get; set; }
        public Nullable<int> khongsudung { get; set; }
        public string ma_chucvu_old { get; set; }
        public string ma_vanphong_old { get; set; }
        public string is_tudong { get; set; }
        public string is_dautien { get; set; }
        public Nullable<int> stt { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
