//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class qlhd_kehoachmuctieu_thang_g
    {
        public System.Guid soid { get; set; }
        public string ma_chinhanh { get; set; }
        public string is_gad { get; set; }
        public string ma_nhanh_gad { get; set; }
        public string ma_loaict { get; set; }
        public Nullable<System.DateTime> ngayct { get; set; }
        public string soct { get; set; }
        public string ma_chucvu { get; set; }
        public string ma_nv { get; set; }
        public string ma_nv_tuyendung { get; set; }
        public Nullable<System.DateTime> thangnam { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<decimal> fyp_canhan_thangtruoc { get; set; }
        public Nullable<decimal> fyp_hethong_thangtruoc { get; set; }
        public Nullable<decimal> fyp_congdon_thangtien_thangtruoc { get; set; }
        public Nullable<decimal> fyp_conthieu_thangtruoc { get; set; }
        public Nullable<decimal> hethong_tructiep_thangtruoc { get; set; }
        public Nullable<decimal> trabai_conthieu_thangtruoc { get; set; }
        public Nullable<decimal> thunhap_dukien_thang { get; set; }
        public Nullable<decimal> fyp_thang { get; set; }
        public Nullable<int> hopdong_thang { get; set; }
        public Nullable<int> fc_tuyendung_tructiep_thang { get; set; }
        public Nullable<int> fc_tongso_thang { get; set; }
        public Nullable<int> fc_hoatdong_thang { get; set; }
        public Nullable<int> fc_tuyendung_moi_thang { get; set; }
        public Nullable<int> fc_thangcap_um { get; set; }
        public Nullable<decimal> tyle_duytri_hientai_thang { get; set; }
        public Nullable<decimal> caithien_thang { get; set; }
        public Nullable<int> hopdong_cankhoiphuc_thang { get; set; }
        public Nullable<int> soluong_hoithao_thang { get; set; }
        public string is_trinhduyet { get; set; }
        public string nguoiduyet1 { get; set; }
        public Nullable<System.DateTime> ngayduyet1 { get; set; }
        public Nullable<int> duyet1 { get; set; }
        public string nguoiduyet2 { get; set; }
        public Nullable<System.DateTime> ngayduyet2 { get; set; }
        public Nullable<int> duyet2 { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngayxoa { get; set; }
        public string nguoixoa { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string phienban { get; set; }
        public string rowlog { get; set; }
        public string database_name { get; set; }
    }
}
